name: CI - Lint and Check

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies for app
        working-directory: ./app
        run: npm install

      - name: Install dependencies for api
        working-directory: ./api
        run: npm install

      - name: Run ESLint on app
        working-directory: ./app
        run: npm run lint -- --max-warnings=0

      - name: Run ESLint on api
        working-directory: ./api
        run: npm run lint -- --max-warnings=0
