name: CI - Lint and Prettier Format

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master
  workflow_dispatch: # Allow manual triggering

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies for app
        working-directory: ./app
        run: npm install

      - name: Install dependencies for api
        working-directory: ./api
        run: npm install

      - name: Run lint for app
        working-directory: ./app
        run: npm run lint

      - name: Run lint for api
        working-directory: ./api
        run: npm run lint

  prettier-format:
    runs-on: ubuntu-latest
    needs: lint  # Ensure prettier-format runs after lint job completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3
        
      - name: Set up Node.js v20
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies for app
        working-directory: ./app
        run: npm install

      - name: Install dependencies for api
        working-directory: ./api
        run: npm install

      - name: Run prettier-format for app
        working-directory: ./app
        run: npm run prettier-format

      - name: Run prettier-format for api
        working-directory: ./api
        run: npm run prettier-format

  commit-changes:
    runs-on: ubuntu-latest
    needs: prettier-format  # Ensure commit happens after prettier-format completes
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add .
          git commit -m "chore: format code with prettier"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/bobbylkchao/blueprint-dev.git ${{ github.head_ref }}
